extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  es6: true
  mocha: true
  node: true
rules:
  import/no-extraneous-dependencies: 0
  no-console: 0
  no-underscore-dangle: 0
  no-confusing-arrow:
    - error
    - allowParens: true
