extends: airbnb
plugins:
  - import
  - jsx-a11y
  - react
env:
  browser: true
  jest: true
rules:
  no-underscore-dangle: 0
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
  react/prefer-stateless-function:
    - off
