# https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html
Resources:
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.watchtowr.io
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: WebsiteS3Bucket
                  - "/*"
  RedirectS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: watchtowr.io
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.watchtowr.io
          # Protocol: https
  # WebsiteCloudFrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName:
  #             Fn::GetAtt:
  #               - WebsiteS3Bucket
  #               - DomainName
  #           Id: WebsiteS3Origin
  #           S3OriginConfig: {}
  #       Enabled: true
  #       HttpVersion: http2
  #       DefaultRootObject: index.html
  #       Aliases:
  #         - watchtowr.io
  #         - www.watchtowr.io
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - GET
  #           - HEAD
  #         Compress: true
  #         TargetOriginId: WebsiteS3Origin
  #         ForwardedValues:
  #           QueryString: true
  #           Cookies:
  #             Forward: none
  #         ViewerProtocolPolicy: redirect-to-https
  #       PriceClass: PriceClass_100
  # WebsiteRoute53ARecords:
  #   Type: "AWS::Route53::RecordSetGroup"
  #   Properties:
  #     HostedZoneName: watchtowr.io.
  #     RecordSets:
  #       - Name: watchtowr.io.
  #         Type: A
  #         AliasTarget:
  #           HostedZoneId: Z2FDTNDATAQYW2
  #           DNSName:
  #             Fn::GetAtt:
  #               - WebsiteCloudFrontDistribution
  #               - DomainName
  #       - Name: www.watchtowr.io.
  #         Type: A
  #         AliasTarget:
  #           HostedZoneId: Z2FDTNDATAQYW2
  #           DNSName:
  #             Fn::GetAtt:
  #               - WebsiteCloudFrontDistribution
  #               - DomainName
