frameworkVersion: "=1.4.0"

service: watchtowr

provider:
  name: aws
  runtime: nodejs4.3
  region: ${file(package.json):config.region}
  stage: ${env:NODE_ENV}
  cfLogs: true
  timeout: 6
  memorySize: 128
  environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:${self:provider.region}:111685254296:table/*

functions:
  api:
    handler: api.handle
    events:
      - http:
          path: graphql
          method: POST
          cors: true
  runner:
    handler: runner.handle
    timeout: 300
    events:
      - schedule: rate(30 minutes)

resources:
  Resources:
    TestsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: TestId
            AttributeType: S
        KeySchema:
          - AttributeName: TestId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:TESTS_TABLE}
    TestRunsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: TestId
            AttributeType: S
          - AttributeName: RunId
            AttributeType: S
        KeySchema:
          - AttributeName: TestId
            KeyType: HASH
          - AttributeName: RunId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:TEST_RUNS_TABLE}
